#!/bin/bash

# ---------------------------------------------------------------------------
# Cloudflare DDNS updater.  
#
# Whenever your public IP changes, run the script. It will work out what your 
# current IP is and poke it into your nominated DNS record.
#
# Assumes you have cloudflare account hosting the dns for some domain, and 
# that you've created an API key with permissions to edit the zone for that 
# domain. The record must be of type "A".
#
# Requires jq to be installed.
# ---------------------------------------------------------------------------

# --- [configuration] -------------------------------------------------------
# Cloudflare Email address of cloudflare account:
email="someone@example.com"
# Cloudflare api token (with edit dns zone permissions):
token="xyz"
# Name of domain hosted by Cloudflare DNS:
domain="example.com"
# Name of record in zone (including the domain, ie: subdomain.domain.com):
record="acme.example.com"
# --- [end configuration] ---------------------------------------------------

function cfget() {
    echo "$(curl "$1" -s -X GET -H "X-Auth-Email: $email" -H "Authorization: Bearer $token")"
}
function cfput() {
    echo "$(curl "$1" -s -X PUT -H "Content-Type: application/json" -H "X-Auth-Email: $email" -H "Authorization: Bearer $token" -d $2)"
}
function bail() {
    echo -e "$1" && exit $2
}

ip="$(curl -s 'https://api.ipify.org?format=json' | jq -r ".ip")"
[[ -z $ip ]] && bail "Error: failed to obtain public ip address:\n$ip" 1
echo "Current public IPv4 address is: $ip"

# verify token validity
result="$(cfget "https://api.cloudflare.com/client/v4/user/tokens/verify")"
success="$(echo "$result" | jq -r ".success")"
[[ $success != "true" ]] && bail "Error: token invalid" 1

# get zone id
result="$(cfget "https://api.cloudflare.com/client/v4/zones?name=$domain")"
success="$(echo "$result" | jq -r ".success")"
[[ $success != "true" ]] && bail "Error: unable to fetch zone id for domain '$domain':\n$result" 1
zoneid="$(echo "$result" | jq -r ".result | .[0] | .id")"

# get record details
result="$(cfget "https://api.cloudflare.com/client/v4/zones/$zoneid/dns_records?name=$record")"
success="$(echo "$result" | jq -r ".success")"
[[ $success != "true" ]] && bail "Error: unable to fetch details for record '$record':\n:$result" 1
count="$(echo "$result" | jq -r ".result | length")"
[[ $count -eq 0 ]] && bail "Error: no record found with name '$record':\n$result" 1
record_id="$(echo "$result" | jq -r ".result | .[0] | .id")"
record_content="$(echo "$result" | jq -r ".result | .[0] | .content")"
record_type="$(echo "$result" | jq -r ".result | .[0] | .type")"
record_ttl="$(echo "$result" | jq -r ".result | .[0] | .ttl")"
record_proxied="$(echo "$result" | jq -r ".result | .[0] | .proxied")"
echo "Current target for DNS record '$record': $record_content"

# stop if the current record target is same as what we want to set
[[ "$record_content" == "$ip" ]] && bail "Success: no update required" 0

# update record details
data="{\"name\":\"$record\",\"content\":\"$ip\",\"type\":\"$record_type\",\"ttl\":$record_ttl,\"proxied\":$record_proxied}"
result="$(cfput "https://api.cloudflare.com/client/v4/zones/$zoneid/dns_records/$record_id" "$data")"
success="$(echo "$result" | jq -r ".success")"
[[ $success != "true" ]] && bail "Error: failed to update dns:\n$result" 1

# done
echo "Success: dns updated"
